- name: Check if Docker is installed
  command: docker --version
  register: docker_version
  ignore_errors: true

- name: Install Docker if not already installed
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release  }} stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        pkg:
          [
            "docker-ce",
            "docker-ce-cli",
            "docker-buildx-plugin",
            "docker-compose-plugin",
            "containerd.io",
          ]
        state: latest
        update_cache: true

  when: docker_version.rc != 0

- name: Create docker volumes directory in hosts
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /opt/volumes/registry/config/
    - /opt/volumes/registry/data/
    - /opt/volumes/loadbalancer/config/
  tags: create_directories

- name: Create internal Network
  docker_network:
    name: "{{ registry_network_name }}"
    ipam_config:
      - subnet: "{{ registry_subnet }}"
        gateway: "{{ registry_gateway }}"
        iprange: "{{ registry_iprange }}"
  tags: create_network