- hosts: load_balancers
  become: true
  tasks:
    - name: Create internal Network
      docker_network:
        name: registry-network
        ipam_config:
          - subnet: 172.23.8.0/24
            gateway: 172.23.8.1
            iprange: 172.23.8.0/24

    - name: Create docker volumes directory in hosts
      command: mkdir -p  /opt/volumes/registry/config/  /opt/volumes/registry/data/  /opt/volumes/loadbalancer/config/

    - name: Copy Registry config file to hosts
      copy:
        src: config.yml
        dest: /opt/volumes/registry/config/config.yml

    - name: Deploy Regisrty Container
      docker_container:
        name: registry
        image: registry:2
        volumes:
          - /opt/volumes/registry/config/config.yml:/etc/distribution/config.yml
          - /opt/volumes/registry/data/:/var/lib/registry
        networks:
          - name: "registry-network"

    - name: Get registry container IP
      set_fact: 
        local_registry_ip: "172.23.8.2"
    
    - name: Gather list of all load balancers
      set_fact:
        all_loadbalancers: "{{ groups['load_balancers'] | map('extract', hostvars, ['ansible_host']) | list }}"

    - name: Filter out the current load balancer
      set_fact:
        backup_loadbalancer_ips: "{{ all_loadbalancers | difference([ansible_host]) }}"

    - name: Template the NGINX config
      template:
        src: nginx.conf.j2
        dest: /opt/volumes/loadbalancer/config/nginx.conf

    - name: Deploy NGINX Loadbalancer container
      docker_container:
        name: nginx
        image: nginx:latest
        state: started
        volumes:
          - /opt/volumes/loadbalancer/config/nginx.conf:/etc/nginx/nginx.conf:ro
        published_ports:
          - 8080:80
        networks:
          - name: "registry-network"

#TODO split into roles
#TODO registry metric location
#TODO complete nginx config