name: Pull Docker Images

on:
  push:
    branches:
    - main

jobs:
  pull_images:
    name: 📥 Pull Images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Run the script
      run: chmod +x pull-common-images.sh && ./pull-common-images.sh nginx alpine hello-world redis
